channels:
- conda-forge
dependencies:
- python=3.12.9
- pip<=25.0.1
- pip:
  - mlflow==2.21.2
  - attrs==25.3.0
  - cloudpickle==3.1.1
  - defusedxml==0.7.1
  - ipython==8.12.3
  - matplotlib==3.10.1
  - numpy==2.1.3
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.2
  - tensorflow==2.19.0
name: mlflow-env
